export const songs = [
  {
    id: 0,
    name: "Лунный свет",
    src: "https://fucmusic.ru/audio/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - Лунный свет.mp3",
    genre: "Pop",
  },
  {
    id: 1,
    name: "Оставь меня",
    src: "https://fucmusic.ru/audio/pop/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - Оставь меня.mp3",
    genre: "Pop",
  },
  {
    id: 2,
    name: "One day (ENG)",
    src: "https://fucmusic.ru/audio/pop/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - One day (ENG).mp3",
    genre: "Pop",
  },
  {
    id: 3,
    name: "SUN (ENG)",
    src: "https://fucmusic.ru/audio/pop/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - SUN (ENG).mp3",
    genre: "Pop",
  },
  {
    id: 4,
    name: "NO (ENG)",
    src: "https://fucmusic.ru/audio/pop/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - NO (ENG).mp3",
    genre: "Pop",
  },
  {
    id: 5,
    name: "Мне лучше (HYPERR POP)",
    src: "https://fucmusic.ru/audio/pop/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - Мне лучше (HYPERR POP).mp3",
    genre: "Pop",
  },
  {
    id: 6,
    name: "Снова",
    src: "https://fucmusic.ru/audio/pop/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - Снова.mp3",
    genre: "Pop",
  },
  {
    id: 7,
    name: "Выбираю жизнь (ПОП РОК)",
    src: "https://fucmusic.ru/audio/rock/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - Выбираю жизнь (ПОП РОК).mp3",
    genre: "Rock",
  },
  {
    id: 8,
    name: "Тростники (INSTRUMENTAL)",
    src: "https://fucmusic.ru/audio/rock/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - Тростники (INSTRUMENTAL).mp3",
    genre: "Rock",
  },
  {
    id: 9,
    name: "Звездочка (ПОП РОК)",
    src: "https://fucmusic.ru/audio/rock/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - Звездочка (ПОП РОК).mp3",
    genre: "Rock",
  },
  {
    id: 10,
    name: "Хлоя (ПОП РОК)",
    src: "https://fucmusic.ru/audio/rock/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - Хлоя (ПОП РОК).mp3",
    genre: "Rock",
  },
  {
    id: 11,
    name: "Дом снег ночь (ДРУГОЕ)",
    src: "https://fucmusic.ru/audio/rock/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - Дом снег ночь (ДРУГОЕ).mp3",
    genre: "Rock",
  },
  {
    id: 12,
    name: "Тонкая натура (ДРУГОЕ)",
    src: "https://fucmusic.ru/audio/rock/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - Тонкая натура (ДРУГОЕ).mp3",
    genre: "Rock",
  },
  {
    id: 13,
    name: "FUK Love",
    src: "https://fucmusic.ru/audio/rap/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - FUK Love.mp3",
    genre: "Rap",
  },
  {
    id: 14,
    name: "Smoke",
    src: "https://fucmusic.ru/audio/rap/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - Smoke.mp3",
    genre: "Rap",
  },
  {
    id: 15,
    name: "Кто ты (ЖЕСТКИЙ РЭП)",
    src: "https://fucmusic.ru/audio/rap/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - Кто ты (ЖЕСТКИЙ РЭП).mp3",
    genre: "Rap",
  },
  {
    id: 16,
    name: "HARD (ЖЕСТКИ РЭП)",
    src: "https://fucmusic.ru/audio/rap/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - HARD (ЖЕСТКИ РЭП).mp3",
    genre: "Rap",
  },
  {
    id: 17,
    name: "Шизофрения (ЖЕСТКИЙ РЭП)",
    src: "https://fucmusic.ru/audio/rap/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - Шизофрения (ЖЕСТКИЙ РЭП).mp3",
    genre: "Rap",
  },
  {
    id: 18,
    name: "Уйду (ПОП РЭП)",
    src: "https://fucmusic.ru/audio/rap/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - Уйду (ПОП РЭП).mp3",
    genre: "Rap",
  },
  {
    id: 19,
    name: "Звезда (ПОП РЭП)",
    src: "https://fucmusic.ru/audio/rap/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - Звезда (ПОП РЭП).mp3",
    genre: "Rap",
  },
  {
    id: 20,
    name: "Спокойно (ПОП РЭП)",
    src: "https://fucmusic.ru/audio/rap/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - Спокойно (ПОП РЭП).mp3",
    genre: "Rap",
  },
  {
    id: 21,
    name: "Летать (ПОП РЭП)",
    src: "https://fucmusic.ru/audio/rap/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - Летать (ПОП РЭП).mp3",
    genre: "Rap",
  },
  {
    id: 22,
    name: "CHERRY JAM (ЭЛЕКТРОННАЯ,BASS HOUSE)",
    src: "https://fucmusic.ru/audio/electronic/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - CHERRY JAM (ЭЛЕКТРОННАЯ,BASS HOUSE).mp3",
    genre: "Electronic",
  },
  {
    id: 23,
    name: "SYNTH",
    src: "https://fucmusic.ru/audio/electronic/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - SYNTH.mp3",
    genre: "Electronic",
  },
  {
    id: 24,
    name: "JALKO",
    src: "https://fucmusic.ru/audio/electronic/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - JALKO.mp3",
    genre: "Electronic",
  },
  {
    id: 25,
    name: "GIVE UP (ПОП,РЭП,ЭЛЕКТРОННАЯ,ЭМО)",
    src: "https://fucmusic.ru/audio/electronic/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - GIVE UP (ПОП,РЭП,ЭЛЕКТРОННАЯ,ЭМО).mp3",
    genre: "Electronic",
  },
  {
    id: 26,
    name: "HOUSE GRAN",
    src: "https://fucmusic.ru/audio/electronic/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - HOUSE GRAN.mp3",
    genre: "Electronic",
  },
  {
    id: 27,
    name: "Без интереса (ЭЛЕКТРОННАЯ,РЭП,ПОП)",
    src: "https://fucmusic.ru/audio/electronic/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - Без интереса (ЭЛЕКТРОННАЯ,РЭП,ПОП).mp3",
    genre: "Electronic",
  },
  {
    id: 28,
    name: "Хуже",
    src: "https://fucmusic.ru/audio/electronic/FUC MUSIC СТУДИЯ ЗВУКОЗАПИСИ - Хуже.mp3",
    genre: "Electronic",
  },
];
