import { Content } from "./components/content/content";
import { Footer } from "./components/footer/footer";
import { Header } from "./components/header/header";
import { Spectrum } from "./components/spectrum/spectrum";
import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["cyrillic"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={`${montserrat.className} relative`}>
        <Header />
        <Content>{children}</Content>
        <Footer />
        <Spectrum />
      </body>
    </html>
  );
}
