import { Provider } from "react-redux";
import { Content } from "./components/content/content";
import { Footer } from "./components/footer/footer";
import { Header } from "./components/header/header";
import { Spectrum } from "./components/spectrum/spectrum";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { store } from "./store/store";

const montserrat = Montserrat({ subsets: ["cyrillic"] });

export const metadata = {
  title: "Fuc Music - студия звукозаписи, Москва, Таганская",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <link
        rel="apple-touch-icon"
        sizes="180x180"
        href="/assets/favicon/apple-touch-icon.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="/assets/favicon/favicon-32x32.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="16x16"
        href="/assets/favicon/favicon-16x16.png"
      />
      <link rel="manifest" href="/assets/favicon/site.webmanifest" />
      <body className={`${montserrat.className} relative`}>
        <Header />
        <Content>{children}</Content>
        <Footer />
        <Spectrum />
      </body>
    </html>
  );
}
